[package]
name = "assigment2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version= "4.4.6", features = ["derive"] }
figlet-rs = "0.1.5"
text_io = "0.1.12"
